[build]
  command = "npm run build"
  publish = "/build"

  [[headers]]
  for = "/pipeline-report"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Basic-Auth = "pipeline:gotpipes? algorand:gotalgos?"
